name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version."
        required: true
        default: "v0.x.x"

jobs:
  build-distribution:
    name: Build distribution 📦
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install pypa/build
        run: python3 -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v7
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: Publish to PyPI 🚀
    timeout-minutes: 5
    needs:
      - build-distribution
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/prefect-deployments-toolkit
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

  create_github_release:
    name: Create a GitHub release 🔖
    timeout-minutes: 5
    needs:
      - publish-to-pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Create a release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd #v1.21.0
        with:
          generateReleaseNotes: true
          tag: ${{ github.event.inputs.version }}
